USE codeup_test_db;

TRUNCATE TABLE albums;

INSERT INTO albums (artist, name, release_date, sales_in_millions, genre)
VALUES ('Michael Jackson', 'Thriller', 1982, 65, 'Pop, rock, R&B'),
       ('Pink Floyd', 'The Dark Side of the Moon', 1973, 45, 'Progressive rock'),
       ('Whitney Houston', 'The Bodyguard', 1992, 44, 'Soundtrack/R&B, soul, pop'),
       ('Meat Loaf', 'Bat Out of Hell', 1977, 43, 'Hard rock, progressive rock'),
       ('Eagles', 'Their Greatest Hits(1971-1975)', 1976, 42, 'Rock, soft rock, folk rock'),
       ('AC/DC', 'Back in Black', 1980, 40, 'Hard rock'),
       ('Bee Gees/Various artists', 'Saturday Night Fever', 1977, 40, 'Disco'),
       ('Fleetwood Mac', 'Rumours', 1977, 40, 'Soft rock'),
       ('Shania Twain', 'Come On Over', 1997, 39, 'Country, pop'),
       ('Led Zeppelin', 'Led Zeppelin IV', 1971, 37, 'Hard rock, heavy metal'),
       ('Alanis Morissette', 'Jagged Little Pill', 1995, 33, 'Alternative rock'),
       ('Celine Dion', 'Falling into You', 1996, 32, 'Pop/Soft rock'),
       ('The Beatles', 'Sgt. Pepper\'s Lonely Hearts Club Band', 1967, 32, 'Rock'),
       ('Eagles', 'Hotel California', 1976, 32, 'Rock, soft rock, folk rock'),
       ('Mariah Carey', 'Music Box', 1993, 32, 'Pop/R&B/Rock'),
       ('Various artists', 'Dirty Dancing', 1987, 32, 'Pop, rock, R&B'),
       ('Celine Dion', 'Let\'s Talk About Love', 1997, 31, 'Pop/Soft rock'),
       ('The Beatles', '1', 2000, 31, 'Rock'),
       ('Adele', '21', 2011, 30, 'Pop, soul'),
       ('The Beatles', 'Abbey Road', 1969, 30, 'Rock'),
       ('Bruce Springsteen', 'Born in the U.S.A.', 1984, 30, 'Rock'),
       ('Dire Straits', 'Brothers in Arms', 1985, 30, 'Rock'),
       ('Whitney Houston', 'Whitney Houston', 1985, 25, 'Pop, R&B'),
       ('James Horner', 'Titanic: Music from the Motion Picture', 1997, 30, 'Soundtrack'),
       ('Madonna', 'The Immaculate Collection', 1990, 30, 'Pop/Dance'),
       ('Metallica', 'Metallica', 1991, 30, 'Thrash metal/heavy metal'),
       ('Michael Jackson', 'Bad', 1987, 30, 'Pop, funk, rock'),
       ('Michael Jackson', 'Dangerous', 1991, 45, 'Rock/Funk/Pop'),
       ('Nirvana', 'Nevermind', 1991, 30, 'Grunge, alternative rock'),
       ('Pink Floyd', 'The Wall', 1979, 30, 'Progressive rock'),
       ('Santana', 'Supernatural', 1999, 30, 'Rock'),
       ('Guns N\' Roses', 'Appetite for Destruction', 1987, 30, 'Metal');